name: Send Leave Application Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install ssmtp
      run: |
        sudo apt-get update
        sudo apt-get install -y ssmtp

    - name: Configure ssmtp
      run: |
        echo "root=$GMAIL_USERNAME" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "mailhub=smtp.gmail.com:587" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "AuthUser=$GMAIL_USERNAME" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "AuthPass=$GMAIL_PASSWORD" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "UseSTARTTLS=YES" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "TLS_CA_File=/etc/ssl/certs/ca-certificates.crt" | sudo tee -a /etc/ssmtp/ssmtp.conf

    - name: Send Email
      env:
        GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      run: |
        echo -e "To: jyotiranjanpanda568@gmail.com\nFrom: $GMAIL_USERNAME\nSubject: Leave Application\n\nDear Jyotiranjan,\n\nI am writing to request leave from July 10 to July 20.\n\nBest regards,\nJohn Doe" | ssmtp jyotiranjanpanda568@gmail.com
